### ISSUE TITLE
Separating images

### ISSUE THREAD

**Issue by oanarosca** [fossasia/gci16.fossasia.org#74]
I think it would be a good idea to put the images into separate folders (student images, mentor images, project images, and other pictures used on the website), in order to keep a nice, organized folder structure. If the mentors agree with this, I would like to work on it (I will also edit the html file so that it will correspond to the new structure and not cause any problems). :blush:

**Comment by Princu7** [comment]
@oanarosca Seems like a nice idea. Also, I looked at the gci 15 site and it follows the same structure like the one mentioned above.

**Comment by tradzik** [comment]
@oanarosca I am for it.

**Comment by tradzik** [comment]
Fixed in https://github.com/fossasia/gci16.fossasia.org/commit/666cd602904e3715987f735a88db893998ed522e

**Comment by oanarosca** [comment]
@tradzik nope, the img paths are still wrong, but I'm working on it.
